### ISSUE TITLE
Include “includeDatasetDetails” field in BeaconAlleleRequest

### ISSUE THREAD

**Issue by mfiume** [ga4gh/beacon-team#10]
If present and true would mean that the response must specify results per dataset.

Useful for owners of beacons with lots of datasets that don’t want to return a detailed response per dataset if this has not been explicitly requested by the user.

**Comment by sdelatorrep** [comment]
+1

**Comment by jrambla** [comment]
+1
It is adding flexibilty, which is usually good when is not overkill for the developers.

**Comment by mcupak** [comment]
Note from the call: default to false.

**Comment by mfiume** [comment]
So if someone explicitly queries a dataset without specifying includeDatasetDetails=true, the response will only include the global response? I think this is good, just seeking clarification.

**Comment by mcupak** [comment]
@mfiume Correct, that's what was agreed on and that's how it's implemented in #50.

**Comment by mfiume** [comment]
Ok, +1
