### ISSUE TITLE
ELIXIR AAI and REMS integration for applying bona fide status (GA4GH Plenary meeting AAI demo)

### ISSUE THREAD

**Issue by juhtornr** [ga4gh/beacon-team#109]
The ELIXIR Reference implementation support ELIXIR AAI and registered access using bona fide status attribute from ELIXIR AAI. Implement support for the process applying bona fide status so that whole process from applying the status and using it can be demonstrated in plenary meeting.

**Comment by susheel** [comment]
Demo'ed successfully at Beacon workshop
