### ISSUE TITLE
Add an “apiVersion” field to BeaconAlleleResponse

### ISSUE THREAD

**Issue by mfiume** [ga4gh/beacon-team#12]
Currently only at Beacon.

Users won’t need to explicitly call the / endpoint to know the API version of the Beacon they are using.

**Comment by mcupak** [comment]
-1

API version is a property of the beacon, i.e. it belongs under /. A beacon will never return different API versions for different variants/responses, so there shouldn't be a need to to have it in BeaconAlleleResponse. The query syntax/semantics might change between different versions of the API, so you could argue that the client should know the version of the API before it executes a query anyway.

**Comment by jrambla** [comment]
+1

It is a sanity check for an asynchronous, distributed system like the one we are building. 
Responses must be auto-suficient in terms of metadata. Each caller could, thus, double check the context from the response itself .
Nothing is impeding the user to receive answers from different servers between "info" call and actual query response, or just having deployed a new version between calls.

**Comment by mcupak** [comment]
Accepted.

**Comment by mfiume** [comment]
Can we revisit this @jrambla? I agree that it makes parsing the result simpler but not sure how much more of an advantage it is over querying the info endpoint once, and remembering the version for every subsequent request. As written, this field is optional, and so the only way I client will be confident in the version is to encode a fallback to look at the info endpoint anyways.

**Comment by jrambla** [comment]
+1 v.0.4

**Comment by sdelatorrep** [comment]
Closing as it is already included in merged PR #92
