### ISSUE TITLE
Use / as info endpoint instead of /info

### ISSUE THREAD

**Issue by mfiume** [ga4gh/beacon-team#13]

**Comment by mcupak** [comment]
This is already a part of the draft schema as listed in #33.

**Comment by jrambla** [comment]
I've mixed feelings on this.
I like removing "/info" if we consider that the root URL is pointing to "beacon" as a resource, in the REST way. But we can not be sure.
On the other hand, In general, we are not using the REST approach for endpoints, like "query".
On the other hand, in another issue, you are suggesting to add "datasets" as endpoint, which is a resource...
Thus, I'll vote to keep both "/" and "/info" and endorse flexibility again. Mapping two distinct endpoints to the same "method" should not be a big deal for any developer, I'm guessing.

**Comment by mcupak** [comment]
Accepted.
