### ISSUE TITLE
Remove “info” fields

### ISSUE THREAD

**Issue by mfiume** [ga4gh/beacon-team#14]
All custom fields should be added as normal fields.

Important: It is developers’ responsibility to check that their custom fields don’t collide with new fields in future API versions.

**Comment by mfiume** [comment]
This is a proposal that was raised in our discussions. I will -1 it.

Does this preclude someone from adding arbitrary metadata in the response? This is an important feature. The GACall object has a map<array<string>> info map, but standardization of terms in this map would require promoting a key in the map to a higher level field, and we wanted to avoid this.

**Comment by uruloki85** [comment]
I also downvote.
As you said, it was discussed in a mail thread (subject Beacon 0.3 API) and in [this Google doc](https://docs.google.com/document/d/1n7qtCBFwsExP_k2GPfWS_PN53Xeh8YxeCBOgyZ5itOw/edit#heading=h.uovhx4rkf4yx) you wrote you already removed all "info" fields but I (we) think it's a bad idea and we should keep it.

**Comment by sdelatorrep** [comment]
I also downvote.
As you said, it was discussed in a mail thread (subject Beacon 0.3 API) and in [this Google doc](https://docs.google.com/document/d/1n7qtCBFwsExP_k2GPfWS_PN53Xeh8YxeCBOgyZ5itOw/edit#heading=h.uovhx4rkf4yx) you wrote you already removed all "info" fields but I (we) think it's a bad idea and we should keep it.

**Comment by jrambla** [comment]
-1
We must clearly distinguish between "official"/reserved words and such that are custom.
We should not rely on developers for issues related to consistency in the API requests/responses.

**Comment by mcupak** [comment]
Rejected.
