### ISSUE TITLE
Make “datasetIds” parameter in BeaconAlleleRequest mandatory.

### ISSUE THREAD

**Issue by mfiume** [ga4gh/beacon-team#16]
Proposal by @mcupak, please elaborate.

**Comment by mcupak** [comment]
This affects includeDatasetDetails (#17), please see https://github.com/ga4gh/beacon-team/issues/17#issuecomment-210127048 for details.

**Comment by jrambla** [comment]
-1
This is forcing to query first for the list of datasets and knowing the ID *before* doing a query.
If we keep this "mandatory" out, and make default for includeDatasetDetails [https://github.com/ga4gh/beacon-team/issues/17](url) as "false", then, the v0.2 query and the v0.3 query are conceptually equal, and we can get a "summary" answer from a Beacon, being the caller agnostic about the Beacon have datasets or not. Makes sense?

**Comment by skeenan** [comment]
+0

**Comment by jdylan** [comment]
-1

**Comment by mcupak** [comment]
Rejected on the call - default to all datasets.
