### ISSUE TITLE
Rename all timestamp fields and change the type to be ISO8601 compliant

### ISSUE THREAD

**Issue by mfiume** [ga4gh/beacon-team#19]
Proposal by Michael Baudis, please elaborate if this isn't sufficient.

“created” to  “createDateTime”
“updated” to “updateDateTime”
http://progenetix.org/Sites/github/mbaudis/biosample/html/api/metadata.html#date-and-time-format-specifications

**Comment by mcupak** [comment]
Removing the proposal label as this issue got multiple +1s in the shared Google Doc.
