### ISSUE TITLE
Querying beacons 

### ISSUE THREAD

**Issue by marchoeppner** [ga4gh/beacon-team#2]
Hi,

I've been following the GA4GH efforts, specifically beacon and mme, for a couple of months. We are in the process of building a variant database and would like to eventually contribute - using both beacon and mme.

At the moment I am trying to see if beacon can be used as part of our processing stage, which will ask for any newly added variant whether it has already been seen in external datasets (g1k, clinvar, etc). Beacon seems the obvious choice, but I am struggling with getting that to work. Specifically, I was hoping to find some sort of unified cli-compatible REST type interface and a list of URLs of beacon-hosting sites. That does not seem to exist, I guess. I google'd a bit, and found e.g. instructions on how to query the beacon over at Sanger and UCSC, but others (e.g. EBI etc) I could not find. 

What would be the best way to integrate beacon queries into our local setup?

Sorry that this is not strictly a development related issue, but I couldn't find another "communications" channel that seemed more appropriate.

Cheers,
Marc

**Comment by mcupak** [comment]
I think your best option is to integrate beacons through the Beacon Network, which provides a unified REST API to query public beacons: https://beacon-network.org

It provides JSON and XML API, its root is here: https://beacon-network.org/api/

You can see a few sample queries here: http://mcupak.github.io/beacon-of-beacons/queries.html

You can query all the beacons at once, a specific subset, or, if you only want to know if any of them have the variant, you can query this aggregate beacon: https://beacon-network.org/api/beacons/bob

There is a mailing list for questions related to the Beacon Network: https://groups.google.com/forum/#!forum/ga4gh-beacon-network

Hope this helps,
Miro
