### ISSUE TITLE
Add data use condition support

### ISSUE THREAD

**Issue by mfiume** [ga4gh/beacon-team#22]

**Comment by mcupak** [comment]
I assume this is about the conditions based on consent codes as per http://dx.doi.org/10.1371/journal.pgen.1005772, in which case it's already a part of the draft schema as listed in #33.

**Comment by mcupak** [comment]
Agreed to postpone to 1.0.

**Comment by sdelatorrep** [comment]
I've created a PR in the [consent codes' repository](https://github.com/ga4gh/ga4gh-consent-policy/pull/4) which contains the spec in protobuf3. 

To everybody: consider recovering the changes in [commit](https://github.com/sdelatorrep/beacon-team/commit/57ff2a049b7640f968f96cce6c2d024055a7cec4) which were finally dropped in merged PR #92

**Comment by juhtornr** [comment]
As Sabela said, she have created protobuf3 version of this specification, it should be merged and this ticket should be closed. 

See: https://github.com/ga4gh/ga4gh-consent-policy/pull/4/files#diff-e9c154965595cff75ec70dab802303d9

**Comment by antbro** [comment]
But this is just Consent Codes. It was agreed we'd support consent codes 
and ADA-M.
The API for ADA-M is also now ready. So please let us accommodate both 
before we close this ticket
Thanks
Tony

--
  Professor Anthony J Brookes
  Department of Genetics
  University of Leicester
  University Road
  Leicester, LE1 7RH, UK
  Tel: +44 (0)116 2523401
  Tel: +44 (0)116 2044767
  Mbl: +44 (0)777 0620396
  Fax: +44 (0)116 2523378
  -
  ** Mundum mutatu errore singillatim
  ** http://libraryofmistakes.com/about
  -
  ** Where is the wisdom we have lost in knowledge?
  ** Where is the knowledge we have lost in information?
  ** T.S. Eliot


Juha Törnroos wrote:

**Comment by sdelatorrep** [comment]
The PR can be merged but, as Tony's just said, the ticket must be kept open. 

I will have a look at [ADA-M protobuf definition](https://github.com/ga4gh/ADA-M/blob/master/ADAM.proto) asap and try to suggest a way to integrate both into the beacon.

**Comment by antbro** [comment]
Thanks!
My preference has always been that we harmonise/unify as much of this as 
possible - with just the specific models of CC and ADA-M distinguishing 
them once included.
I also think the ideal model should allow a user to employ one or both, 
or indeed any other model that might come along.
Perhaps you could present a proposed solution on a future Beacon call?
Cheers
Tony


Sabela wrote:

**Comment by sdelatorrep** [comment]
Hello everybody!
I've just done a PR with a proposal for including both CC and ADA-M: #110 
Please, review it and provide feedback.
Thanks!

**Comment by uruloki85** [comment]
Please, remember that [this](https://github.com/ga4gh/ga4gh-consent-policy/pull/4) PR in CC repo is pending since de 4th of July and nobody but Juha has provided any feedback.

**Comment by sdelatorrep** [comment]
Please, remember that [this](https://github.com/ga4gh/ga4gh-consent-policy/pull/4) PR in CC repo is pending since de 4th of July and nobody but Juha has provided any feedback.

**Comment by susheel** [comment]
+1 Merge & Close

**Comment by susheel** [comment]
Surely this must be closed now! @mcupak @juhtornr ?
