### ISSUE TITLE
Beacon assembly version, query?

### ISSUE THREAD

**Issue by marchoeppner** [ga4gh/beacon-team#3]
Hi,

started a topic on the google group, but figured this is more of a feature request/issue:

Are there plans to make the assembly version of a beacon dataset a query'able field? 

Basically, I noticed that while a beacon will take note of the assembly version I am specifying to generate an answer, I don't see an obvious way to filter beacons / datasets prior to submitting a query. Essentially, I would have to query any given variant twice (GRCh37 and GRCh38) to make sure that I get as much information as possible.

This would create unnecessary load and would create a lot more queries for me to sift through and reconcile. It would be easier if I could partition the list of beacons by assembly version first, and then submit appropriate queries to each set.

**Comment by mcupak** [comment]
I hope my reply on the mailing list answers this question now:

https://groups.google.com/d/msg/ga4gh-beacon-network/qbJJigXV1zc/aNAuR_V8BQAJ
