### ISSUE TITLE
Determine the contents of the repository

### ISSUE THREAD

**Issue by mcupak** [ga4gh/beacon-team#30]
I think we need to discuss what exactly we keep in this repository with respect to the schema. I can think of 3 options:

1. Isolated beacon-related Avro IDL files. Basically what we currently have in [schema directory](https://github.com/ga4gh/beacon-team/tree/master/schema) as a result of #27.
2. All the schemas, i.e. sync with [ga4gh/schemas](https://github.com/ga4gh/schemas/) as the upstream repository, as suggested in https://github.com/ga4gh/beacon-team/pull/27#issuecomment-208240302.
3. Beacon-related schemas with a subset of tools from [ga4gh/schemas](https://github.com/ga4gh/schemas/) adopted to beacons, i.e. develop beacons as an independent artifact with [ga4gh/schemas](https://github.com/ga4gh/schemas/) as a dependency.

**Comment by mcupak** [comment]
I think my vote goes to option 3 - I'd like our stuff to be sort of self-contained, i.e. compilable and not referring to things outside this repository (hence not option 1), and developed as an independent artifact (hence not option 2).

**Comment by mfiume** [comment]
+1 for option 3

**Comment by jrambla** [comment]
I've not yet a formed opinion on this.
