### ISSUE TITLE
Support for variant frequencies

### ISSUE THREAD

**Issue by marchoeppner** [ga4gh/beacon-team#4]
Hi,

I saw a comment indicating that frequency information will be supported in future beacon API releases. Is there a time line for that? We would like to move some of our data over to beacons, but would definitely need frequency information for that to make sense. 

/Marc

**Comment by mcupak** [comment]
I hope my reply on the mailing list answers this question now:

https://groups.google.com/d/msg/ga4gh-beacon-network/qbJJigXV1zc/aNAuR_V8BQAJ

For reference, here's a link to frequency info in the beacon spec:

https://github.com/ga4gh/schemas/blob/beacon/src/main/resources/avro/beacon.avdl#L147
