### ISSUE TITLE
Move data use to separate repositories

### ISSUE THREAD

**Issue by mcupak** [ga4gh/beacon-team#47]
Consider moving data use specifications to separate repositories so that they can be released/versioned independently from beacon. Beacon should treat their releases as dependencies.

**Comment by mcupak** [comment]
+1 from Jordi and Marc

**Comment by antbro** [comment]
+1

Tony



________________________________

**Comment by jrambla** [comment]
@mcupak Could you link the repo here, please?

**Comment by mcupak** [comment]
The repository is here: https://github.com/ga4gh/ga4gh-consent-policy

It looks like the specification has not been moved yet from its branch in this repository: https://github.com/ga4gh/beacon-team/tree/consent_code

**Comment by mcupak** [comment]
Update: [ga4gh-consent-policy repository](https://github.com/ga4gh/ga4gh-consent-policy) now contains the consent code spec.

**Comment by antbro** [comment]
Hi Miro

Thanks for working on this (which I assume is the previous work now moved to a separate repository, correct?)

It would be good to start on what we agreed - creating the API for ADA-M, and ensuring this and the one for CC are aligned though both independent. Vagelis from my teams stands ready to work with you on this, but needs your help to get things started

Tony



________________________________
