### ISSUE TITLE
Release artifact to Maven Central

### ISSUE THREAD

**Issue by mcupak** [ga4gh/beacon-team#51]

**Comment by mcupak** [comment]
Update: There has been some recent development on a [related core API issue](https://github.com/ga4gh/schemas/issues/278). Since we're using the same group ID, it makes sense for us to synchronize with this work and set up our repository and artifacts the same way. I'd suggest adding this to 0.4 as a non-blocker issue (and optionally postponing it to a later release depending on the progress on https://github.com/ga4gh/schemas/issues/278 with respect to our deadline).

**Comment by jrambla** [comment]
Sorry Miro,

I'm not familiarised with this stuff, and guessing I'll not be the only one
;-), could you kindly introduce it in the next CC or so?
Best!

El dt., 28 juny 2016 , 17:17, Miro Cupak <notifications@github.com> va
escriure:

**Comment by jrambla** [comment]
@mcupak @mfiume, could you address my comment on June 29th, please?

**Comment by mcupak** [comment]
I can do you one better Jordi, I can just describe it here, as it's simple to explain. Feel free to raise this on the next call if more info is needed.

Both our and core APIs have a `pom.xml` file in the repository used by Maven, a common build tool for Java projects. This allows us to easily generate Java data model from our spec. By default, Maven, and other build tools using its infrastructure, look for artifacts in the central repository.

Pushing beacon Java artifacts to Maven central would make it easy for people to develop on top of beacon - no need to clone the repository from GitHub and build it locally, or even add any custom repository configuration. Just add it to your Java project, and it will be downloaded automatically. Essentially, the central repository is where commonly used libraries typically end up.

In a way, this is a convenience feature for developers using beacon, but also ties to other processes and practices you might have in place in an enterprise setting. For example, the fact that the core API was not initially published to a Maven repository made one of the organizations using it publish those schemas with their own group ID. This would be good to avoid for beacon in order to prevent further confusion.

There is a fixed set of processes and rules an artifact has to conform to in order to be accepted to the central repository - this issue is about configuring beacon to conform to these rules and ultimately release it to the repository. Most of the changes are going to be made to `pom.xml`, this issue does not affect the semantics of our spec.

**Comment by saifEBI** [comment]
How do I self-assign this? Thanks, Saif

**Comment by mbaudis** [comment]
@saifEBI You need to become a team member... Request at https://github.com/orgs/ga4gh/teams/beacon/members
=> @skeenan , @kozbo

**Comment by saifEBI** [comment]
HI guys, I need a usable groupId for the project or I need proof of ownership of the org.ga4gh domain to push the artifact. Does anyone have any suggestions?  Thanks

https://issues.sonatype.org/browse/OSSRH-34681?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel

**Comment by mcupak** [comment]
We should stick with the current group ID if possible. You shouldn't need to verify the domain, that has already been done by @kozbo (https://issues.sonatype.org/browse/OSSRH-23361).

@saifEBI You can try contacting @kozbo. I'm not exactly sure what the next step is, maybe we just need to add our keys somewhere.

**Comment by kozbo** [comment]
Should be good to go, granted access yesterday. Let me know if you need anything else to gain the right access rights.

**Comment by saifEBI** [comment]
Deployment almost done. Having issues with pom authentication when running command 
mvn nexus-staging:release

**Comment by saifEBI** [comment]
Just got back to this. Almost there all I need to do is create a  staging repository under org.ga4gh on Sonnatype and then I should be able to push to that. Branch for release created with release ready pom.xml and settings.xml

**Comment by susheel** [comment]
Just looping in @rishidev to help setting up a staging repo to push the Maven artifact to.

**Comment by saifEBI** [comment]
Pushed https://oss.sonatype.org/content/repositories/snapshots/org/ga4gh/beacon/0.4.0-SNAPSHOT/

**Comment by saifEBI** [comment]
Project can now be pulled using  the dependency given below in a pom. If someone can verify this then this ticket can be closed.

 <dependency> 
<groupId>org.ga4gh</groupId>
 <artifactId>beacon</artifactId>
 <version>0.4.0-SNAPSHOT</version>
</dependency>

**Comment by saifEBI** [comment]
<dependency> 
<groupId>org.ga4gh</groupId>
 <artifactId>beacon</artifactId>
 <version>0.4.0-SNAPSHOT</version>
</dependency>

**Comment by saifEBI** [comment]
This deployment is tied to a public key registered to saifu@ebi.ac.uk as recipient uploaded to pgp.mit.edu.
I'm not sure what steps we need to take to generate a public key which is usable by any developer.

**Comment by saifEBI** [comment]
Documentation for getting deployment authorisation here.

https://github.com/ga4gh/beacon-team/wiki/Maven-Central-Repository-Deployment.

settings.xml edited to be generic for any developer.

**Comment by susheel** [comment]
Related Pull Request #116

**Comment by susheel** [comment]
Related Pull Request #116
