### ISSUE TITLE
Consider adding beaconId to the Beacon response

### ISSUE THREAD

**Issue by mfiume** [ga4gh/beacon-team#52]
The response currently includes datasetId, but not beaconId. Having a beaconId in the response would help resolve the source of the query in applications that may query multiple Beacons simultaneously.

**Comment by mcupak** [comment]
I think this was misfiled, beacon ID is in the response:

https://github.com/ga4gh/beacon-team/blob/develop/src/main/resources/avro/beacon.avdl#L243

Closing.
