### ISSUE TITLE
Centralized BeaconError codes and messages

### ISSUE THREAD

**Issue by sduvaud** [ga4gh/beacon-team#54]
Maybe of interest to have a centralized list of possible Beacon errors with code and message which can be shared by the whole Beacon community.

**Comment by jrambla** [comment]
+1. @sduvaud Could you provide us with your first approach? @mcupak, @sdelatorrep I'm guessing that any Beacon developer has already some sort of error list, although probably short, is that true? Is it easy to share and discuss with Severine?
I'm also guessing that we are considering the typical REST HTTP-based error codes.
And I'm guessing too, that the Reference Server should have worked on it too.
My 2,3,4 cents.  ;-)

**Comment by sduvaud** [comment]
I have no example to provide to date. In Beacon for arrayMap, an error is thrown when one mandatory param is missing or when it is of wrong type,... We also have an error when the database is down, etc...

**Comment by jrambla** [comment]
Probably, we can start having a list of the errors you already expect. Then
joining errors from Sabela, Miro and others... thus we'll compile a list of
"consensus" errors.

**Comment by sduvaud** [comment]
Here is what we have for now:

1. Issues with user input:
reference name is not present
reference name not valid
position not present
position not a number
No dataset provided
Incorrect dataset(s)
Alternate bases not defined
Alternate bases not supported

2. Server-side issue:
Internal error, DB returned a value but post check is not valid.

**Comment by jrambla** [comment]
@sdelatorrep, could you extend this with Elixir Beacon errors, please?

**Comment by sdelatorrep** [comment]
These are the errors that currently can be thrown in the Elixir Beacon we developed:
1. 40X
Missing mandatory parameters: referenceName, position/start and/or assemblyId
Dataset not found
Unauthenticated users cannot access this dataset
The reference genome of this dataset X does not match the provided value
Invalid alternateBases parameter, it can only be [ACTG]+
Invalid referenceBases parameter, it can only be [ACTG]+

2. 50X
Any unexpected server side error.

**Comment by jrambla** [comment]
@sdelatorrep do we have specific errors in the 40x and 50x range? Or is it a generic error and we are being specific in the error message text?

**Comment by sdelatorrep** [comment]
@jrambla We use the following specific codes:
- 412 Precondition Failed -> Missing mandatory parameters: referenceName, position/start and/or assemblyId
- 400 -> Failed to convert value of type 'java.lang.String' to required type 'java.lang.Integer'; nested exception is java.lang.NumberFormatException: For input string: X
- 404 Not found -> Dataset not found
- 401 Unauthorized -> Unauthenticated users cannot access this dataset
- 412 Precondition Failed -> The reference genome of this dataset X does not match the provided value
- 412 Precondition Failed -> Invalid alternateBases parameter, it can only be [ACTG]+
- 412 Precondition Failed -> Invalid referenceBases parameter, it can only be [ACTG]+

**Comment by sdelatorrep** [comment]
The following was discussed and decided during the Beacon meeting at Hinxton in May:
- to use 400 (Bad request) instead of 412
- to use 401 (Unauthorised) when an authenticated user tries to access a protected resource
- to use 403 (Forbidden) when 
-- the resource is protected for all users, or 
-- the user is authenticated but s/he is not granted for this resource
