### ISSUE TITLE
Community level Beacon identifier's assignment

### ISSUE THREAD

**Issue by sduvaud** [ga4gh/beacon-team#55]
Currently, the Beacon identifier is just an ID, assigned by the developer of the Beacon.
Of course, it is everybody’s best interest to use a unique ID, and in the worth case it shouldn’t be a problem if the ID is not unique.  Anyway, it may be a good practise to set up a kind of central authority to assign Beacon unique identifiers.

**Comment by jrambla** [comment]
Couldn't we use the reversed namespace approach?  i.e. org.ega-archive.beacon

**Comment by mcupak** [comment]
+1, the reverse domain approach sounds like a good idea.

**Comment by antbro** [comment]
+1

Tony





________________________________

**Comment by sdelatorrep** [comment]
+1
