### ISSUE TITLE
Describe how to query without reference bases

### ISSUE THREAD

**Issue by mcupak** [ga4gh/beacon-team#59]
The spec requires specifying `referenceBases` and `alternateBases`. Some beacons don't store reference bases. Is this a case that should be supported by the spec? If so, should we consider making the parameter optional?

**Comment by antbro** [comment]
+1


Miro Cupak wrote:

**Comment by jrambla** [comment]
+1

**Comment by mitsuhashi** [comment]
+1

Hi Miro,
Thanks for sparing your time at GA4GH 4th plenary meeting. 

Nobutaka

**Comment by mbaudis** [comment]
+1

**Comment by sdelatorrep** [comment]
+1 to include this in v0.4

**Comment by mcupak** [comment]
This proposal was discussed during the workshop yesterday and rejected. Reference bases remain a mandatory parameter as it is easy to fetch the reference for beacons that don't store it in the database directly.

**Comment by mbaudis** [comment]
But not for structural, anything with a considerable size. So no reference bases if one of the "end" parameters is specified.

Michael.

**Comment by antbro** [comment]
And what about a 3 base deletion?
Where do we draw the line?
Could be easier just to make it always optional?
Tony


Michael Baudis wrote:
> But not for structural, anything with a considerable size. So no 
> reference bases if one of the "end" parameters is specified.
>
> Michael.
>
>
>

**Comment by mbaudis** [comment]
@antbro I think the "if one of the end" positions makes this explicit. I'm anyway for optional, but this seems a good solution - if you specify an end, you fulfil a specific requirement.

**Comment by antbro** [comment]
Hi Michael

We have to two things to consider...

1) the 'Reference Allele Sequence' and
2) the fuzziness of the region we're searching for it in

Whether or not we have to specify the ref allele sequence 'Reference 
Allele Sequence' is challenged by the fact that it will be easy for 
SNPs, harder for indels, and impossible for SVs. So my question was how 
we know when we have to include a 'Reference Allele Sequence'

I do not understand why this is influenced by (or guided by) whether or 
not we are searching within a precise start-end region or a fuzzy region

T





Michael Baudis wrote:

**Comment by mbaudis** [comment]
> I do not understand why this is influenced by (or guided by) whether or
> not we are searching within a precise start-end region or a fuzzy region

The "if end, then no ref needed..." proposal is independent of fuzziness (aka imprecision ...). It is just "you provide the sequence being altered, **OR** you give the coordinates".

And if `end` == `start`, you solve the reference requirement in a sneaky but explicit way even for single bases.

So, while I understand the specification of `reference_bases` for single replacements, and understand the current use for small dels (ref >> alt; e.g. ref `ATCGTA`, alt `A` == deletion of 5 bases), I'm not particularly fond of it; but there are sensible ways to query around this if implementing the "if not ref than end else fail" paradigm.

(I'm the mediator here, right?)

**Comment by mbaudis** [comment]
@mcupak Re-opening. There was general consensus before to make `reference_bases` optional, so this needs explanation.

> This proposal was discussed during the workshop yesterday and rejected. Reference bases remain a mandatory parameter as it is easy to fetch the reference for beacons that don't store it in the database directly.

Reference bases have to be optional for imprecise and range queries, and per se only apply to SNV/small indels. So they only are specified when

* an exact position is being queried
* `alternate_bases` are being provided

In summary this needs a documentation about these conditional interpretations.

**Comment by mbaudis** [comment]
Closing this, since in documentation now "N" allele documented as permitted value for unknown, which solves this (if interpreted as "any").
