### ISSUE TITLE
API still works with 1-based

### ISSUE THREAD

**Issue by aishmitk** [ga4gh/beacon-team#70]
Hi. I was messing around on the beacon network, and realized that all of the positions in which there was a mutation in our database, you guys showed there to be one successfully. I looked at the request that was being made, and it showed that you guys switched from the 1-based coordinate system to the 0-based one, as the position went from x to x-1 (as written in FAQ).

What I don't understand is, how are you guys successfully finding if a mutation exists or doesn't exist, when we are still using a 1-based coordinate system for our API? I have tested with multiple positions, chromosomes, alleles etc. and the beacon network returns the same result as our 1-based API. Are you converting to 0-based, then back to 1-based before the request is sent to us?

**Comment by mcupak** [comment]
@aishmitk That's exactly what we do. We have a "canonical" internal representation for all the parameters, and then do the conversion to the format expected by the individual beacons.

Feel free to use this for questions related to the Beacon Network next time (although confusingly named, we're trying to limit this repository to the API spec): https://groups.google.com/forum/#!forum/ga4gh-beacon-network
