### ISSUE TITLE
Add support for exact matches of indels

### ISSUE THREAD

**Issue by mfiume** [ga4gh/beacon-team#9]
As per: https://github.com/ga4gh/beacon-team/tree/developer-faq

No regular expressions patterns.

Example of asking for a deletion: reference=CG & alternate=C
Example of asking for an insertion: reference=C & alternate=CG

**Comment by mcupak** [comment]
Isn't this already supported through referenceBases and alternateBases?

**Comment by jrambla** [comment]
Probably YES, but we want to make it explicit what we are planning to support in a given version.
This "issue" could be a side effect of translating the document to a set of issues.
